import { useNavigate, useRouterState, useSearch } from "@tanstack/react-router";
import {
  ChevronRight,
  Download,
  FolderOpen,
  Gauge,
  ListOrdered,
  Logs,
  Menu,
  Plus,
  Rss,
  Search as SearchIcon,
  Settings,
} from "lucide-react";
import type { ReactNode } from "react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
// Layout-persistence hook comes from the panels package itself; the registry
// resizable wrapper (regenerated by the shadcn upgrade) no longer re-exports it
import { useDefaultLayout } from "react-resizable-panels";
import { CommandPalette } from "@/components/CommandPalette";
import { FilterSidebar } from "@/components/layout/FilterSidebar";
import { MenuBar } from "@/components/layout/MenuBar";
import { StatusBar } from "@/components/layout/StatusBar";
import { TabNav } from "@/components/layout/TabNav";
import { AppearanceMenu } from "@/components/layout/ThemeToggle";
import { AddTorrentDialog, openAddTorrentDialog } from "@/components/torrent/AddTorrentDialog";
import { StatusSelect } from "@/components/torrent/StatusSelect";
import { Button } from "@/components/ui/button";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useGlobalHotkeys } from "@/hooks/useGlobalHotkeys";
import { useIsMobile } from "@/hooks/useIsMobile";
import { useTitleSpeed } from "@/hooks/useTitleSpeed";
import { cn } from "@/lib/utils";
import { useUiStore } from "@/stores/ui";

/** Persisted layout of the main split panels (auto-saved to localStorage after dragging) */
function useMainLayout() {
  return useDefaultLayout({ id: "qiubi-main", panelIds: ["filter-sidebar", "content"] });
}

/** Mobile drawer navigation pages (page navigation beyond the desktop sidebar filters) */
const MOBILE_NAV = [
  { to: "/", icon: Download, label: "Torrents" },
  { to: "/dashboard", icon: Gauge, label: "Dashboard" },
  { to: "/categories", icon: FolderOpen, label: "Categories" },
  { to: "/rss", icon: Rss, label: "RSS" },
  { to: "/search", icon: SearchIcon, label: "Search" },
  { to: "/log", icon: Logs, label: "Log" },
  { to: "/settings", icon: Settings, label: "Settings" },
] as const;

/**
 * App shell —— qBittorrent native layout
 *
 * Desktop (≥768px): menu bar + toolbar + draggable split panels (filter sidebar | content) + status bar
 * Mobile: compact top bar (hamburger + add) + full-width content; menu/navigation/filters all tucked into drawers
 */
export function AppLayout({ children }: { children: ReactNode }) {
  useGlobalHotkeys();
  useTitleSpeed();
  const isMobile = useIsMobile();
  const { sidebarVisible, statusBarVisible } = useUiStore();
  const { defaultLayout, onLayoutChanged } = useMainLayout();
  /** The sidebar (category/tag tree) is a filter exclusive to the torrent list and only mounts on the list route;
   *  other routes (Dashboard/RSS/Settings…) are full-width, avoiding the confusion of "clicked the sidebar but the URL did not change" */
  const pathname = useRouterState({ select: (st) => st.location.pathname });
  const sidebarActive = sidebarVisible && pathname === "/";
  const [navOpen, setNavOpen] = useState(false);
  const [filterOpen, setFilterOpen] = useState(false);

  return (
    <div className="flex h-screen flex-col overflow-hidden">
      {isMobile ? (
        /* --- Mobile top bar --- */
        <header className="flex h-12 shrink-0 items-center gap-1 border-b bg-card px-2">
          <Button
            variant="ghost"
            size="icon"
            className="size-9"
            onClick={() => setNavOpen(true)}
            aria-label="Menu"
          >
            <Menu className="h-5 w-5" />
          </Button>
          <span className="font-semibold">qiubi</span>
          <div className="ml-auto flex items-center gap-0.5">
            <AppearanceMenu className="size-9" iconClassName="size-5" />
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="size-9"
            onClick={() => setFilterOpen(true)}
            aria-label="Filters"
          >
            <ListOrdered className="h-5 w-5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="size-9"
            onClick={() => openAddTorrentDialog()}
            aria-label="Add"
          >
            <Plus className="h-5 w-5" />
          </Button>
        </header>
      ) : (
        <>
          <MenuBar />
          {/* Global tab navigation (same as official qBT): global search on the left + Transfers/Search/RSS/Log/Settings + add torrent on the right */}
          <TabNav />
        </>
      )}

      <div className="min-h-0 flex-1">
        {isMobile ? (
          /* Mobile: full-width content */
          <main className="h-full overflow-y-auto p-3">{children}</main>
        ) : sidebarActive ? (
          <ResizablePanelGroup
            id="qiubi-main"
            defaultLayout={defaultLayout}
            onLayoutChanged={onLayoutChanged}
          >
            <ResizablePanel
              id="filter-sidebar"
              defaultSize="18%"
              minSize="12%"
              className="border-r"
            >
              <FilterSidebar />
            </ResizablePanel>
            <ResizableHandle />
            <ResizablePanel id="content">
              <main className="h-full overflow-y-auto p-4 md:p-6">{children}</main>
            </ResizablePanel>
          </ResizablePanelGroup>
        ) : (
          <main className="h-full overflow-y-auto p-4 md:p-6">{children}</main>
        )}
      </div>

      {statusBarVisible && <StatusBar />}

      {/* Mobile: main navigation drawer */}
      <MobileNavSheet open={navOpen} onOpenChange={setNavOpen} />
      {/* Mobile: filter drawer (status + reuses FilterSidebar categories/tags) */}
      <Sheet open={filterOpen} onOpenChange={setFilterOpen}>
        <SheetContent side="left" className="data-[side=left]:w-72 p-0">
          <SheetHeader className="border-b p-3">
            <SheetTitle className="text-sm">Filters</SheetTitle>
          </SheetHeader>
          {/* Single scroll container: the wrapper flexes to the sheet's
              height and FilterSidebar's own overflow is disabled in-sheet
              via h-auto/overflow-visible, killing the nested scrollbar */}
          <div className="min-h-0 flex-1 overflow-y-auto [&_aside]:h-auto [&_aside]:overflow-visible">
            <MobileStatusFilter />
            <FilterSidebar onSelect={() => setFilterOpen(false)} />
          </div>
        </SheetContent>
      </Sheet>

      {/* Global overlays */}
      <CommandPalette />
      <AddTorrentDialog />
    </div>
  );
}

function MobileNavSheet({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="left" className="data-[side=left]:w-72 p-0">
        <SheetHeader className="border-b p-3">
          <SheetTitle className="text-sm">qiubi</SheetTitle>
        </SheetHeader>
        <nav className="space-y-1 p-2">
          {MOBILE_NAV.map((item) => (
            <button
              key={item.to}
              type="button"
              className={cn(
                "flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-foreground",
              )}
              onClick={() => {
                navigate({ to: item.to });
                onOpenChange(false);
              }}
            >
              <item.icon className="h-4 w-4" />
              {t(item.label)}
              <ChevronRight className="ml-auto h-4 w-4 opacity-40" />
            </button>
          ))}
        </nav>
      </SheetContent>
    </Sheet>
  );
}

/** Status dropdown at the top of the mobile filter drawer (equivalent to the desktop toolbar row, writes URL ?status=) */
function MobileStatusFilter() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const urlSearch = useSearch({ strict: false }) as { status?: string };
  const status = urlSearch.status ?? "all";
  return (
    <div className="border-b p-3">
      <div className="pb-1.5 text-xs font-semibold text-muted-foreground">{t("Status")}</div>
      <StatusSelect
        value={status}
        className="w-full"
        onValueChange={(v) => {
          navigate({
            to: "/",
            search: (prev: Record<string, string | undefined>) => {
              const next: Record<string, string | undefined> = {
                ...prev,
                status: v === "all" ? undefined : (v ?? undefined),
              };
              for (const k of Object.keys(next)) if (!next[k]) delete next[k];
              return next;
            },
            replace: true,
          });
        }}
      />
    </div>
  );
}
